//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapTuan7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Course
    {
        public int Course_Id { get; set; }
        public string Course_Name { get; set; }
        public byte[] Images { get; set; }
        public string Details { get; set; }
    }
}
