//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapTuan7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Student_Assignment
    {
        public int AS_Id { get; set; }
        public Nullable<int> Assignment_Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public string Decriptions { get; set; }
        public string File { get; set; }
    }
}
